blank_issues_enabled: true
contact_links:
  - name: ğŸ“§ ãƒ¡ãƒ¼ãƒ«
    url: mailto:toyamasoujinn@gmail.com
    about: ãƒ¡ãƒ¼ãƒ«ã§ã®å•ã„åˆã‚ã›ã¯ã“ã¡ã‚‰ã¾ã§
  - name: ğŸ¦ Twitter
    url: https://x.com/ToYamaSoujin
    about: Twitterã§ã®é€£çµ¡ã¯ã“ã¡ã‚‰ã¾ã§
